GET {{domain}}/{{server_name}}/test

###
POST {{domain}}/{{server_name}}/test
Content-Type: application/json
Accept-Language: en-US

{
  "id": 1,
  "email": "test@qq",
  "address": {
    "province": "guangdong",
    "city": "shenzhen"
  }
}
