server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          predicates:
          - Path=/info
          uri: http://localhost:9000/info
        - id: framework_route
          predicates:
            - Path=/framework/**
          uri: http://localhost:9001
        - id: url-proxy
          uri: https://blog.csdn.net
          predicates:
            - Path=/csdn/**
          filters:
            - RewritePath=/csdn/(?<segment>.*), /$\{segment}

